app/controllers/announcement.py
from datetime import datetime

from flask import Blueprint, request, g, flash, render_template, redirect, url_for
from werkzeug.exceptions import abort

from app.database.db import get_db
from app.controllers.auth import login_required


bp = Blueprint('announcement', __name__, url_prefix='/announcement')

@bp.route('/list')
@login_required
def list_announcement():
	db = get_db()
	announcement_data = db.execute(
		'SELECT ann.announcement_id, ann.announcement_title, ann.announcement_content, '
		'ann.creation, user.username FROM tabAnnouncement ann '
		'LEFT JOIN tabUser user ON user.user_id = ann.created_by_user '
		'ORDER BY ann.creation DESC'
	).fetchall()

	return render_template('announcement/list_announcement.html', data=announcement_data)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def create_announcement():
	if g.user['role'] != "Teacher":
		abort(403, "Not permitted to view this page.")

	if request.method == 'POST':
		title = request.form['title']
		message = request.form['message']

		db = get_db()
		error = None

		if not (title and message):
			error = 'Please fill all data.'

		if not error:
			db.execute(
				'INSERT INTO tabAnnouncement (announcement_title, announcement_content, '
				'created_by_user, creation) VALUES (?, ?, ?, ?)',
				[title, message, g.user['user_id'], datetime.now()]
			)

			db.commit()
			flash("Announcement created successfully", 'success')
			return redirect(url_for("announcement.list_announcement"))

		flash(error, 'error')

	return render_template('announcement/new_announcement.html')


@bp.route('/delete/<int:announcement_id>', methods=['POST'])
@login_required
def delete_announcement(announcement_id):
	if g.user['role'] != "Teacher":
		abort(403, "Not permitted to view this page.")

	db = get_db()
	db.execute(
		'DELETE FROM tabAnnouncement WHERE announcement_id = ?', [announcement_id]
	)
	db.commit()

	flash("Announcement deleted successfully", 'info')
	return redirect(url_for('announcement.list_announcement'))

app/templates/announcement/list_announcement.html
{% extends 'base.html' %}

{% block title %}Announcements {{ data.event_id }}{% endblock %}


{% block style %}
<style>
	.announcement-container {
		background-color: #f2f2f2;
		border: 1px solid #ccc;
	}
	
</style>
{% endblock %}


{% block content %}
	{% if g and g.user and g.user.role == "Teacher" %}
	<div class="d-flex justify-content-end my-4">
		<a class="btn btn-success" href="{{ url_for('announcement.create_announcement') }}">
			Add New Announcement
			<span class="fa fa-plus"></span>
		</a>
	</div>
	{% endif %}



	{% if data %}

		{% for announcement in data %}

		<div class="announcement-container w-80 m-auto mt-5 p-3">
			<h5>{{ announcement.announcement_title }}</h5>
			<p>{{ announcement.announcement_content }}</p>
			<p>{{ announcement.creation|format_datetime }}</p>
			<p>{{ announcement.username }}</p>


			{% if g and g.user and g.user.role == "Teacher" %}
			<form action="{{ url_for('announcement.delete_announcement', announcement_id=announcement.announcement_id) }}" method="post">
				<input class="btn btn-danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
			</form>
			{% endif %}

		</div>

		{% endfor %}

	{% else %}
	<div>
		Nothing to show.
	</div>
	{% endif %}

{% endblock %}

app/templates/announcement/new_announcement.html
{% extends 'base.html' %}

{% block title %}New Announcement{% endblock %}


{% block style %}
<style>

</style>
{% endblock %}


{% block content %}
<main class="">
	<form method="Post">
		<h1 class="">Create New Announcement</h1>

		<div class="form-floating">
			<input type="text" class="form-control" name="title" placeholder="Title" required>
			<label for="title">Title</label>
		</div>
		<div class="form-floating">
			<textarea class="form-control" style="height:150px" name="message" placeholder="Message" rows="4"></textarea>
			<label for="message">Message</label>
		</div>
		<div class="d-grid">
			<button class="btn btn-primary" type="submit">Create Announcement</button>
		</div>
	</form>
</main>
{% endblock %}