app/controllers/event.py
from datetime import datetime

from flask import Blueprint, request, g, flash, render_template, redirect, url_for
from werkzeug.exceptions import abort

from app.database.db import get_db
from app.controllers.auth import login_required


bp = Blueprint('event', __name__, url_prefix='/event')

@bp.route('/<int:event_id>')
def view_event(event_id):
	db = get_db()

	event_data = db.execute(
		'SELECT * FROM tabEvent '
		'LEFT JOIN tabQuiz ON tabQuiz.event_id = tabEvent.event_id '
		'WHERE tabEvent.event_id = ?', [event_id]
	).fetchone()

	if not event_data:
		flash('Cannot find the specified event.', 'error')

	return render_template('event/view_event.html', data=event_data)


@bp.route('/group/<int:event_year>')
def view_event_group(event_year):
	db = get_db()

	events = db.execute(
		'SELECT * FROM tabEvent '
		'LEFT JOIN tabQuiz ON tabQuiz.event_id = tabEvent.event_id '
		'WHERE tabEvent.event_year = ?', [event_year]
	).fetchall()

	events_data = {}

	for row in events:
		year_group = events_data.setdefault(row['event_year'], {})
		country_group = year_group.setdefault(row['event_country'], [])
		country_group.append(dict(row))

	if not events_data:
		flash("No events found for the specified year.", 'error')

	return render_template('event/view_event_group.html', data=events_data)


@bp.route('/new', methods=['GET', 'POST'])
@login_required
def create_event():
	if g.user['role'] != "Teacher":
		abort(403, "Not permitted to view this page.")

	if request.method == 'POST':
		country = request.form['country']
		year = request.form['year']
		title = request.form['title']
		description = request.form['description']

		db = get_db()
		error = None

		if not (country and year and title):
			error = 'Please fill all data.'

		if country not in ["Italy", "Germany"]:
			error = 'Please select a country from list'
		elif int(year) not in range(1000, 3000):
			error = 'Invalid year'

		if not error:
			try:
				cursor = db.execute(
					'INSERT INTO tabEvent (event_country, event_year, event_title, event_description, '
					'created_by_user, creation) VALUES (?, ?, ?, ?, ?, ?)',
					[country, year, title, description, g.user['user_id'], datetime.now()]
				)

				event_id = cursor.lastrowid
				db.commit()
			except db.IntegrityError:
				error = f"An event with same details already exist."
			else:
				flash("Event created successfully", 'success')
				return redirect(url_for("event.view_event", event_id=event_id))

		flash(error, 'error')

	return render_template('event/new_event.html')


@bp.route('/edit/<int:event_id>', methods=['GET', 'POST'])
@login_required
def edit_event(event_id):
	if g.user['role'] != "Teacher":
		abort(403, "Not permitted to view this page.")

	db = get_db()
	error = None

	if request.method == 'POST':
		description = request.form['description']

		event_data = db.execute(
			'SELECT * FROM tabEvent WHERE event_id = ?', [event_id]
		).fetchone()

		if description == event_data['event_description']:
			error = "No changes in the document."

		if not error:
			db.execute(
				'UPDATE tabEvent SET event_description = ?, modified_by_user = ?, '
				'modified = ? WHERE event_id = ?',
				[description, g.user['user_id'], datetime.now(), event_id]
			)
			db.commit()

			flash("Event Updated Successfully.", 'success')
			return redirect(url_for('event.view_event', event_id=event_id))

		flash(error, 'error')

	event_data = db.execute(
		'SELECT * FROM tabEvent where event_id = ?', [event_id]
	).fetchone()

	return render_template('event/edit_event.html', data=event_data)


@bp.route('/delete/<int:event_id>', methods=['POST'])
@login_required
def delete_event(event_id):
	if g.user['role'] != "Teacher":
		abort(403, "Not permitted to view this page.")

	db = get_db()
	db.execute(
		'DELETE FROM tabEvent WHERE event_id = ?', [event_id]
	)
	db.commit()

	flash("Event deleted successfully", 'info')
	return redirect(url_for('main.timeline'))

app/controllers/main.py
from flask import Blueprint, render_template

from app.database.db import get_db


bp = Blueprint('main', __name__)

@bp.route('/')
def timeline():
	db = get_db()

	events = db.execute(
		'SELECT * FROM tabEvent '
		'ORDER BY event_year ASC, event_title ASC'
	).fetchall()

	events_data = {}

	for row in events:
		year_group = events_data.setdefault(row['event_year'], {})
		country_group = year_group.setdefault(row['event_country'], [])
		country_group.append(dict(row))

	return render_template('main/timeline.html', data=events_data)

app/templates/main/timeline.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}


{% block style %}
	<style>
		:root {
			--timeline_height: {{ '100%' if (data.items() | length) > 2 else '50%' }};
		}
	</style>

	<link rel="stylesheet" href="{{ url_for('static', filename='css/timeline.css') }}">
{% endblock %}


{% block content %}
<main>
	{% if g and g.user and g.user.role == "Teacher" %}
	<div class="d-flex justify-content-end my-4">
		<a class="btn btn-success" href="{{ url_for('event.create_event') }}">
			Add New Event
			<span class="fa fa-plus"></span>
		</a>
	</div>
	{% endif %}


	{% set left_country = "Germany" %}
	{% set right_country = "Italy" %}

	{% if data %}
	<div class="timeline">

		<div class="row h3 text-uppercase text-center p-3">
			<div class="col-6">{{ left_country }}</div>
			<div class="col-6">{{ right_country }}</div>
		</div>

		<div class="container">

			{% for year, event_group in data.items() %}
			<div class="event_group row my-3">
				<div class="event_left col-6 text-end">
					<div class="event_year">
						<a href="{{ url_for('event.view_event_group', event_year=year) }}">{{ year }}</a>
					</div>
					{% for event in event_group[left_country] %}
					<div class="event_title">
						<a href="{{ url_for('event.view_event', event_id=event.event_id) }}">
							{{ event.event_title }}
						</a>
					</div>
					{% endfor %}
				</div>
				<div class="event_right col-6 event_right">
					<div class="event_year">
						<a href="{{ url_for('event.view_event_group', event_year=year) }}">{{ year }}</a>
					</div>
					{% for event in event_group[right_country] %}
					<div class="event_title">
						<a href="{{ url_for('event.view_event', event_id=event.event_id) }}">{{ event.event_title }}</a>
					</div>
					{% endfor %}
				</div>
			</div>
			{% endfor %}

		</div>
	</div>
	{% else %}
		<p>No event to show. Please add an event.</p>
	{% endif %}
</main>
{% endblock %}